var hierarchy =
[
    [ "Application", null, [
      [ "Biblioteca.Model.App", "class_biblioteca_1_1_model_1_1_app.html", null ]
    ] ],
    [ "Biblioteca.Model.Bibliotecario", "class_biblioteca_1_1_model_1_1_bibliotecario.html", null ],
    [ "Biblioteca.Model.BibliotecarioTest", "class_biblioteca_1_1_model_1_1_bibliotecario_test.html", null ],
    [ "Biblioteca.Controller.ControllerDelete", "class_biblioteca_1_1_controller_1_1_controller_delete.html", null ],
    [ "Biblioteca.Controller.ControllerDeleteTest", "class_biblioteca_1_1_controller_1_1_controller_delete_test.html", null ],
    [ "Biblioteca.Controller.ControllerHomepage", "class_biblioteca_1_1_controller_1_1_controller_homepage.html", null ],
    [ "Biblioteca.Controller.ControllerHomepageTest", "class_biblioteca_1_1_controller_1_1_controller_homepage_test.html", null ],
    [ "Biblioteca.Controller.ControllerInfo", "class_biblioteca_1_1_controller_1_1_controller_info.html", null ],
    [ "Biblioteca.Controller.ControllerInfoTest", "class_biblioteca_1_1_controller_1_1_controller_info_test.html", null ],
    [ "Biblioteca.Controller.ControllerLibri", "class_biblioteca_1_1_controller_1_1_controller_libri.html", null ],
    [ "Biblioteca.Controller.ControllerLibriTest", "class_biblioteca_1_1_controller_1_1_controller_libri_test.html", null ],
    [ "Biblioteca.Controller.ControllerLogin", "class_biblioteca_1_1_controller_1_1_controller_login.html", null ],
    [ "Biblioteca.Controller.ControllerLoginTest", "class_biblioteca_1_1_controller_1_1_controller_login_test.html", null ],
    [ "Biblioteca.Controller.ControllerLogout", "class_biblioteca_1_1_controller_1_1_controller_logout.html", null ],
    [ "Biblioteca.Controller.ControllerPopupLibro", "class_biblioteca_1_1_controller_1_1_controller_popup_libro.html", null ],
    [ "Biblioteca.Controller.ControllerPopupLibroTest", "class_biblioteca_1_1_controller_1_1_controller_popup_libro_test.html", null ],
    [ "Biblioteca.Controller.ControllerPopupPrestiti", "class_biblioteca_1_1_controller_1_1_controller_popup_prestiti.html", null ],
    [ "Biblioteca.Controller.ControllerPopupPrestitiTest", "class_biblioteca_1_1_controller_1_1_controller_popup_prestiti_test.html", null ],
    [ "Biblioteca.Controller.ControllerPopupStudenti", "class_biblioteca_1_1_controller_1_1_controller_popup_studenti.html", null ],
    [ "Biblioteca.Controller.ControllerPopupStudentiTest", "class_biblioteca_1_1_controller_1_1_controller_popup_studenti_test.html", null ],
    [ "Biblioteca.Controller.ControllerPrestiti", "class_biblioteca_1_1_controller_1_1_controller_prestiti.html", null ],
    [ "Biblioteca.Controller.ControllerPrestitiTest", "class_biblioteca_1_1_controller_1_1_controller_prestiti_test.html", null ],
    [ "Biblioteca.Controller.ControllerResetPassword", "class_biblioteca_1_1_controller_1_1_controller_reset_password.html", null ],
    [ "Biblioteca.Controller.ControllerResetPasswordTest", "class_biblioteca_1_1_controller_1_1_controller_reset_password_test.html", null ],
    [ "Biblioteca.Controller.ControllerRitorno", "class_biblioteca_1_1_controller_1_1_controller_ritorno.html", null ],
    [ "Biblioteca.Controller.ControllerRitornoTest", "class_biblioteca_1_1_controller_1_1_controller_ritorno_test.html", null ],
    [ "Biblioteca.Controller.ControllerStudenti", "class_biblioteca_1_1_controller_1_1_controller_studenti.html", null ],
    [ "Biblioteca.Controller.ControllerStudentiTest", "class_biblioteca_1_1_controller_1_1_controller_studenti_test.html", null ],
    [ "Biblioteca.Controller.ControllerSuccesso", "class_biblioteca_1_1_controller_1_1_controller_successo.html", null ],
    [ "Biblioteca.Controller.ControllerSuccessoTest", "class_biblioteca_1_1_controller_1_1_controller_successo_test.html", null ],
    [ "Biblioteca.Model.Database", "class_biblioteca_1_1_model_1_1_database.html", null ],
    [ "Biblioteca.Model.Libro", "class_biblioteca_1_1_model_1_1_libro.html", null ],
    [ "Biblioteca.Model.Prestito", "class_biblioteca_1_1_model_1_1_prestito.html", null ],
    [ "Biblioteca.Model.Studente", "class_biblioteca_1_1_model_1_1_studente.html", null ]
];